function [c,ceq] = constraint_MuscleOptimization(in1)
%constraint_MuscleOptimization
%    [C,CEQ] = constraint_MuscleOptimization(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2022 22:12:43

M_h = in1(:,1);
M_k = in1(:,2);
M_t = in1(:,3);
a_G = in1(:,6);
a_GA = in1(:,9);
a_H = in1(:,7);
a_IP = in1(:,5);
a_RF = in1(:,4);
a_TA = in1(:,8);
c = zeros(0,0);
if nargout > 1
    ceq = [M_h+a_G.*2.43e+2+a_H.*2.43e+2-a_IP.*4.86e+2-a_RF.*(4.86e+2./5.0);M_k+a_G.*1.05e+2-a_RF.*4.2e+1;M_t+a_GA.*1.56e+2-a_TA.*1.3e+2];
end
